# -*- coding: utf-8 -*-
"""Sigmoid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19sQBbz7uyT77PxBRXkR-hb7IjVQ9He_P
"""

import numpy as np

def sigmoid(x):
  return 1 / (1 + np.exp(-x))


input = [-10, 0, 10]

for i in input:
  print(f'x = {i}, sigmoid value = {sigmoid(i)}')