# -*- coding: utf-8 -*-
"""ReLU.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IwFPayYh3CWsUqFtA5zPqMe_NlSYuesv
"""

import numpy as np

def ReLU(x):
  return max(0, x)


test = np.array([-10, 0, 10])

for i in test:
  print(f'Relu on x = {i} gives: {ReLU(i)}')