# -*- coding: utf-8 -*-
"""Softmax.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SusP9Y2tIWBd0WTW9Zqtxj-KFUoabt4M
"""

import numpy as np

def softmax(x):
  e = np.exp(x)

  output = []

  for i in e:
    output.append(i / e.sum())

  return output


input = [-10, 0, 10]

print(np.sum(softmax(input)))