# -*- coding: utf-8 -*-
"""tanh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dxSkS7Plxc8XJ98Lw10Jj2oPx2kGoUJK
"""

import numpy as np

def tanh(x):
  e = np.exp(2 * x)

  return (e - 1) / (e + 1)


input = [-10, 0, 10]

for i in input:
  print(f'x = {i} tanh = {tanh(i)}')